/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Laboratorio-Info
 */
public class tela_GUI extends javax.swing.JFrame {

    /**
     * Creates new form tela_GUI
     */
    public tela_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        action_menos_btn = new javax.swing.JButton();
        action_mais_btn = new javax.swing.JButton();
        action_multi_btn = new javax.swing.JButton();
        action_divisa_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valor1_txt = new javax.swing.JTextField();
        valor2_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculadora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel1.setLayout(null);

        action_menos_btn.setText("-");
        action_menos_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_menos_btnActionPerformed(evt);
            }
        });
        jPanel1.add(action_menos_btn);
        action_menos_btn.setBounds(100, 140, 49, 23);

        action_mais_btn.setText("+");
        action_mais_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_mais_btnActionPerformed(evt);
            }
        });
        jPanel1.add(action_mais_btn);
        action_mais_btn.setBounds(40, 140, 49, 23);

        action_multi_btn.setText("*");
        action_multi_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_multi_btnActionPerformed(evt);
            }
        });
        jPanel1.add(action_multi_btn);
        action_multi_btn.setBounds(170, 140, 49, 23);

        action_divisa_btn.setText("/");
        action_divisa_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_divisa_btnActionPerformed(evt);
            }
        });
        jPanel1.add(action_divisa_btn);
        action_divisa_btn.setBounds(230, 140, 49, 23);

        jLabel1.setText("Valor 1:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 60, 56, 14);

        jLabel2.setText("Valor 2:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 100, 56, 14);
        jPanel1.add(valor1_txt);
        valor1_txt.setBounds(120, 60, 141, 20);

        valor2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor2_txtActionPerformed(evt);
            }
        });
        jPanel1.add(valor2_txt);
        valor2_txt.setBounds(120, 100, 141, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void action_menos_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_menos_btnActionPerformed
        Controller.Funcoes_DAO.func_menos();
    }//GEN-LAST:event_action_menos_btnActionPerformed

    private void action_mais_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_mais_btnActionPerformed
        Controller.Funcoes_DAO.func_mais();
    }//GEN-LAST:event_action_mais_btnActionPerformed

    private void action_multi_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_multi_btnActionPerformed
        Controller.Funcoes_DAO.func_multi();
    }//GEN-LAST:event_action_multi_btnActionPerformed

    private void action_divisa_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_divisa_btnActionPerformed
       Controller.Funcoes_DAO.func_divisa();
    }//GEN-LAST:event_action_divisa_btnActionPerformed

    private void valor2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor2_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton action_divisa_btn;
    public static javax.swing.JButton action_mais_btn;
    public static javax.swing.JButton action_menos_btn;
    public static javax.swing.JButton action_multi_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField valor1_txt;
    public static javax.swing.JTextField valor2_txt;
    // End of variables declaration//GEN-END:variables
}
